### ISSUE TITLE
User Profile Inaccessible When Title in the Company is Set to Empty

### ISSUE THREAD

**Issue by Jh0wjso** [operately/operately#561] opened 2024-06-11 16:38 UTC
When the user sets their role to an empty value and saves it, they are subsequently unable to access their own profile. This issue prevents the user from viewing or editing their profile, which could impact their ability to use the platform effectively.

**Steps to Reproduce:**

1. Navigate to the user profile settings.
2. Set the Title in the company field to an empty value.
3. Save the changes.
4. Attempt to access the user profile again.

**Expected Result:**
The user should be able to access their profile regardless of the role field being empty.

**Actual Result:**
The user is unable to access their profile after setting the role to an empty value.

**Attachments:**

1. **Screenshot:**

   ![image](https://github.com/operately/operately/assets/68076306/a787ed47-4225-4a05-bff1-689c1bd26702)

2. **Video Demonstration, after Set Title in the company as empty:**

   [Video Link](https://github.com/operately/operately/assets/68076306/7bafa1d6-9d31-417d-bee5-cd152dce64b7)

**Comment by shiroyasha** [comment] 2024-07-09 12:16
No longer an issue. Can't reproduce. Closing.

**Closed by shiroyasha** 2024-07-09 12:16 UTC
Labels: bug
